drop table if exists friends;
drop table if exists film_genres;
drop table if exists likes;
droP table if exists genres;
drop table if exists users;
drop table if exists films;
drop table if exists rating_mpa;

CREATE TABLE IF NOT EXISTS rating_mpa (
  id integer generated by default as identity not null PRIMARY KEY,
  name varchar(64) not null unique
);

CREATE TABLE IF NOT EXISTS films (
  id integer generated by default as identity not null PRIMARY KEY,
  name varchar(255) not null,
  description varchar(1024),
  release_date date,
  duration integer not null,
  rate integer not null,
  rating_mpa_id integer not null references rating_mpa(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS users (
  id integer generated by default as identity not null PRIMARY KEY,
  name varchar(64) not null,
  email varchar(128) not null unique,
  login varchar(128) not null unique,
  birthday date not null
);

CREATE TABLE IF NOT EXISTS genres (
  id integer generated by default as identity not null PRIMARY KEY,
  name varchar(128) not null unique
);

CREATE TABLE IF NOT EXISTS likes (
  user_id integer not null references users(id) on delete cascade,
  film_id integer not null references films(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id integer not null references films(id) on delete cascade,
  genre_id integer not null references genres(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS friends (
  first_user_id integer not null references users(id) on delete cascade,
  second_user_id integer not null references users(id) on delete cascade
);

